"""Add site_id column to Product table

Revision ID: a510c391b2b0
Revises: 
Create Date: 2025-06-05 15:06:59.254857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a510c391b2b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('site_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_product_site_id'), 'product', ['site_id'], unique=False)
    op.create_index(op.f('ix_scraper_error_site_id'), 'scraper_error', ['site_id'], unique=False)
    op.create_index(op.f('ix_vendor_listing_site_id'), 'vendor_listing', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_listing_site_id'), table_name='vendor_listing')
    op.drop_index(op.f('ix_scraper_error_site_id'), table_name='scraper_error')
    op.drop_index(op.f('ix_product_site_id'), table_name='product')
    op.drop_column('product', 'site_id')
    # ### end Alembic commands ###
