"""Remove site_id from Product table

Revision ID: eb57351c3616
Revises: a510c391b2b0
Create Date: 2025-06-05 15:16:33.526750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb57351c3616'
down_revision: Union[str, None] = 'a510c391b2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_site_id'), table_name='product')
    op.drop_column('product', 'site_id')
    op.drop_index(op.f('ix_scraper_error_site_id'), table_name='scraper_error')
    op.drop_index(op.f('ix_vendor_listing_site_id'), table_name='vendor_listing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vendor_listing_site_id'), 'vendor_listing', ['site_id'], unique=False)
    op.create_index(op.f('ix_scraper_error_site_id'), 'scraper_error', ['site_id'], unique=False)
    op.add_column('product', sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_product_site_id'), 'product', ['site_id'], unique=False)
    # ### end Alembic commands ###
