
services:
  api:
    build: .
    image: komprice-base
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [db, redis]
  worker:
    image: komprice-base
    command: ["python", "workers/dispatcher.py"]
    env_file: .env
    environment:
      - PYTHONPATH=/app
    depends_on: [db, redis]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: komprice
    ports: ["5432:5432"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
